name: simple_linkedin_login
description: Linked-in login client to help with login into a flutter app easily.
version: 0.1.0+2
repository: https://github.com/rockers007/simple_linkedin_login.git
homepage: https://www.rockersinfo.com/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # to use http client methods
  http: ^0.13.0

  # to show web pages within the app
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true